const ADMIN_LOGIN = {
  LOAD: 'LOAD_ADMIN_LOGIN',
  SUCCESS: 'SUCCESS_ADMIN_LOGIN',
  FAIL: 'FAIL_ADMIN_LOGIN'
};

const USER_LIST = {
  LOAD: 'LOAD_USER_DATA',
  SUCCESS: 'SUCCESS_USER_DATA',
  FAIL: 'FAIL_USER_DATA'
};

const DELETE_USER = {
  LOAD: 'LOAD_DELETE_USER',
  SUCCESS: 'SUCCESS_DELETE_USER',
  FAIL: 'FAIL_DELETE_USER'
};

const TOPIC_LIST = {
  LOAD: 'LOAD_TOPIC_DATA',
  SUCCESS: 'SUCCESS_TOPIC_DATA',
  FAIL: 'FAIL_TOPIC_DATA'
};

const DELETE_TOPIC = {
  LOAD: 'LOAD_DELETE_TOPIC',
  SUCCESS: 'SUCCESS_DELETE_TOPIC',
  FAIL: 'FAIL_DELETE_TOPIC'
};

const ADD_TOPIC = {
  LOAD: 'LOAD_ADD_TOPIC',
  SUCCESS: 'SUCCESS_ADD_TOPIC',
  FAIL: 'FAIL_ADD_TOPIC'
};

const UPDATE_TOPIC = {
  LOAD: 'LOAD_UPDATE_TOPIC',
  SUCCESS: 'SUCCESS_UPDATE_TOPIC',
  FAIL: 'FAIL_UPDATE_TOPIC'
};

const ADD_QUESTION = {
  LOAD: 'LOAD_ADD_QUESTION',
  SUCCESS: 'SUCCESS_ADD_QUESTION',
  FAIL: 'FAIL_ADD_QUESTION'
};

const UPDATE_QUESTION = {
  LOAD: 'LOAD_UPDATE_QUESTION',
  SUCCESS: 'SUCCESS_UPDATE_QUESTION',
  FAIL: 'FAIL_UPDATE_QUESTION'
};

const QUESTION_LIST = {
  LOAD: 'LOAD_QUESTION_DATA',
  SUCCESS: 'SUCCESS_QUESTION_DATA',
  FAIL: 'FAIL_QUESTION_DATA'
};

const DELETE_QUESTION = {
  LOAD: 'LOAD_DELETE_QUESTION',
  SUCCESS: 'SUCCESS_DELETE_QUESTION',
  FAIL: 'FAIL_DELETE_QUESTION'
};

const GET_QUESTION = {
  LOAD: 'LOAD_GET_QUESTION',
  SUCCESS: 'SUCCESS_GET_QUESTION',
  FAIL: 'FAIL_GET_QUESTION'
};

const UPLOAD_FILE = {
  LOAD: 'LOAD_UPLOAD_FILE',
  SUCCESS: 'SUCCESS_UPLOAD_FILE',
  FAIL: 'FAIL_UPLOAD_FILE',
  CLEAR: 'CLEAR_UPLOAD_FILE'
};
const DELETE_FILE = {
  LOAD: 'LOAD_DELETE_FILE',
  SUCCESS: 'SUCCESS_DELETE_FILE',
  FAIL: 'FAIL_DELETE_FILE'
};

const DISCUSSION_LIST = {
  LOAD: 'LOAD_DISCUSSION_LIST',
  SUCCESS: 'SUCCESS_DISCUSSION_LIST',
  FAIL: 'FAIL_DISCUSSION_LIST'
};

const DELETE_DISCUSS = {
  LOAD: 'LOAD_DELETE_DISCUSS',
  SUCCESS: 'SUCCESS_DELETE_DISCUSS',
  FAIL: 'FAIL_DELETE_DISCUSS'
};

const HINT_LIST = {
  LOAD: 'LOAD_HINT_DATA',
  SUCCESS: 'SUCCESS_HINT_DATA',
  FAIL: 'FAIL_HINT_DATA'
};

const ADD_HINT = {
  LOAD: 'LOAD_ADD_HINT',
  SUCCESS: 'SUCCESS_ADD_HINT',
  FAIL: 'FAIL_ADD_HINT'
};

const DELETE_HINT = {
  LOAD: 'LOAD_DELETE_HINT',
  SUCCESS: 'SUCCESS_DELETE_HINT',
  FAIL: 'FAIL_DELETE_HINT'
};

const UPDATE_HINT = {
  LOAD: 'LOAD_UPDATE_HINT',
  SUCCESS: 'SUCCESS_UPDATE_HINT',
  FAIL: 'FAIL_UPDATE_HINT'
};

export {
  ADMIN_LOGIN,
  USER_LIST,
  DELETE_USER,
  TOPIC_LIST,
  DELETE_TOPIC,
  QUESTION_LIST,
  DELETE_QUESTION,
  ADD_TOPIC,
  UPDATE_TOPIC,
  ADD_QUESTION,
  GET_QUESTION,
  UPDATE_QUESTION,
  UPLOAD_FILE,
  DELETE_FILE,
  DISCUSSION_LIST,
  DELETE_DISCUSS,
  HINT_LIST,
  ADD_HINT,
  DELETE_HINT,
  UPDATE_HINT
};
